[package]
name = "iron_tank"
version = "0.1.0"
authors = ["kanari"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"


[workspace]
members = [
    "tank_cell",
]