[package]
name = "iron_tank"
version = "0.1.1"
authors = ["kanari"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace]
members = [
    "tank_cell",
    "tank_cli",
    "tank_client",
    "tank_server",
    "tank_core",
]