[package]
name = "tank_cli"
version = "0.2.0"
authors = ["Kanari <iovo7c@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
tank_core = { path = "../tank_core"}