[package]
name = "tank_cell"
version = "0.1.0"
authors = ["kanari"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seccomp-sys = "0.1.3"
libc = "0.2.82"
clap = "2.33"